source 'https://mirrors.tuna.tsinghua.edu.cn/git/CocoaPods/Specs.git'
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'live-stream-APP' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'HWPanModal', '~> 0.6.0'
  # Pods for live-stream-APP

end
